### ISSUE TITLE
Cannot work with Stream

### ISSUE THREAD

**Issue by leo-gan** [rpgmaker/MessageShark#14]
Hi,
Your serializer shows good results in my tests. 
But now I'm going to change the interface to work with Stream, because it is the most used way to work with serializers. Is there a way to use these signatures?
  void Serialize(object root, Stream stream);
and 
  object Deserialize(Stream stream);

Thanks!

**Comment by rpgmaker** [comment]
There is two method already for textreader and textwriter which convert the underlying object to stringbuilder or pointer to string. That should work for use in a case of small object like an 100mb json.

Thanks,

**Comment by rpgmaker** [comment]
For the Serialize method you simply need to create a custom class that route your writes to my CustomBuffer class. 

For the Deserialize, you need to simply have your own implementation of ReadNextBytes, GetNextLength, and MoveToNextBytes method which will interact with your Stream.

Thanks,

**Comment by leo-gan** [comment]
I didn't find any examples how to do this. Can you provide examples, please?

Regards,

Leonid Ganeline

**Comment by rpgmaker** [comment]
The issue is that you will need to write IL code that will call your class instead of mine by subclassing CustomBuffer. As for the deserialization it is going to be a little more work. If you give me a day, I can implement it and you can see what I did.

Sorry that I don't have any google examples.

Thanks,

**Comment by leo-gan** [comment]
Thank you for fast response!
I'm using this code now, but it doesn't work. Could you, please, help with
it?
      public  void Serialize(object root, Stream stream)
        {
            var buf = MessageShark.MessageSharkSerializer.Serialize(root);
            stream.Write(buf, 0, buf.Length);
        }

        public object Deserialize(Stream stream)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                 stream.CopyTo(ms);
                return
MessageShark.MessageSharkSerializer.Deserialize<object>(ms.ToArray());
            }


Regards,

Leonid Ganeline
Microsoft Integration MVP (BizTalk Server)
http://geekswithblogs.net/leonidganeline/

**Comment by rpgmaker** [comment]
What error message are you getting? The serialization for object at this time only support primitive types not complex object. The only to make it work is to use reflection to determine the correct type at runtime and select the right serialization for it using something like this.


public delegate object DeserializeWithTypeDelegate(string value);
        public delegate string SerializeWithTypeDelegate(object value);

        static ConcurrentDictionary<string, DeserializeWithTypeDelegate> _deserializeWithTypes =
            new ConcurrentDictionary<string, DeserializeWithTypeDelegate>();

        static ConcurrentDictionary<Type, SerializeWithTypeDelegate> _serializeWithTypes =
            new ConcurrentDictionary<Type, SerializeWithTypeDelegate>();

        static MethodInfo _getSerializerMethod = _jsonType.GetMethod("GetSerializer", BindingFlags.NonPublic | BindingFlags.Static);
        static Type _netJSONSerializerType = typeof(NetJSONSerializer<>);

        public static string Serialize(Type type, object value) {
            return _serializeWithTypes.GetOrAdd(type, _ => {
                var name = String.Concat(SerializeStr, type.FullName);
                var method = new DynamicMethod(name, _stringType, new[] { _objectType }, restrictedSkipVisibility: true);

                var il = method.GetILGenerator();
                var genericMethod = _getSerializerMethod.MakeGenericMethod(type);
                var genericType = _netJSONSerializerType.MakeGenericType(type);

                var genericSerialize = genericType.GetMethod(SerializeStr, new[] { type });

                il.Emit(OpCodes.Call, genericMethod);

                il.Emit(OpCodes.Ldarg_0);
                if (type.IsClass) 
                    il.Emit(OpCodes.Isinst, type);
                else il.Emit(OpCodes.Unbox_Any, type);
                
                il.Emit(OpCodes.Callvirt, genericSerialize);

                il.Emit(OpCodes.Ret);

                return method.CreateDelegate(typeof(SerializeWithTypeDelegate)) as SerializeWithTypeDelegate;
            })(value);
        }

        public static string Serialize(object value) {
            return Serialize(value.GetType(), value);
        }

        public static object Deserialize(Type type, string value) {

            return _deserializeWithTypes.GetOrAdd(type.FullName, _ => {
                var name = String.Concat(DeserializeStr, type.FullName);
                var method = new DynamicMethod(name, _objectType, new[] { _stringType }, restrictedSkipVisibility: true);

                var il = method.GetILGenerator();
                var genericMethod = _getSerializerMethod.MakeGenericMethod(type);
                var genericType = _netJSONSerializerType.MakeGenericType(type);

                var genericDeserialize = genericType.GetMethod(DeserializeStr, new[] { _stringType });

                il.Emit(OpCodes.Call, genericMethod);

                il.Emit(OpCodes.Ldarg_0);
                il.Emit(OpCodes.Callvirt, genericDeserialize);

                if (type.IsClass)
                    il.Emit(OpCodes.Isinst, type);
                else {
                    il.Emit(OpCodes.Box, type);
                }

                il.Emit(OpCodes.Ret);

                return method.CreateDelegate(typeof(DeserializeWithTypeDelegate)) as DeserializeWithTypeDelegate;
            
            })(value);
        }

**Comment by rpgmaker** [comment]
I copied that code from netjson. But using similar code you can adjust it to work also for messageshark.

Thanks,

**Comment by rpgmaker** [comment]
Were you able to temporary modify it to work for you or do you want me to make the changes?

**Comment by leo-gan** [comment]
IMO, work with Streams must be there. It is the right way to send/receive
data, right? So I would prefer if I could work directly with Streams and do
not slow down your serializer with additional unnecessary transformations.

Regards,

Leonid Ganeline
Microsoft Integration MVP (BizTalk Server)
http://geekswithblogs.net/leonidganeline/

**Comment by rpgmaker** [comment]
I will work on creating a wrapper that uses stream for both writer and
reader instead using my custom buffer and byte array this weekend for you.
And still kept that logic for generating correct type when object type is
used.

Thanks,

**Comment by leo-gan** [comment]
Thanks a lot!!!!!!!!!!!!

Regards,

Leonid Ganeline
Microsoft Integration MVP (BizTalk Server)
http://geekswithblogs.net/leonidganeline/

**Comment by rpgmaker** [comment]
I have added the method to serialize and deserialize using object. I also added the method to allow writing directly to a stream object using both generic and object type. 

The reading from a Stream requires a little bit more logic. So for now, I will add a method that just read the entire stream so it uses the internal method that uses byte[] .

**Comment by rpgmaker** [comment]
Done. I added the nuget as 1.0.2.

Thanks,
